# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import somemes.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, default='no-img-professor.png', null=True, upload_to=somemes.core.models.upload_location, verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Meme',
                'verbose_name_plural': 'Memes',
            },
        ),
    ]
